#!/usr/bin/env bash
#
# Install Nginx and expose the pawd-bridge API to the internet.
# Run with sudo on Linux, or as root on macOS (Homebrew).
#
# Usage:
#   ./install-nginx-bridge.sh [--domain DOMAIN] [--port 80] [--bridge-port 3001]
#
# Options:
#   --domain DOMAIN   Optional. If set, configures server_name for SSL (run certbot after).
#   --port PORT       Nginx listen port (default: 80)
#   --bridge-port     Bridge listen port (default: 3001)
#   --skip-install    Skip Nginx installation, only write config
#

set -e

# Defaults
DOMAIN=""
NGINX_PORT=80
BRIDGE_PORT=3001
SKIP_INSTALL=false

# Parse args
while [[ $# -gt 0 ]]; do
  case $1 in
    --domain)
      DOMAIN="$2"
      shift 2
      ;;
    --port)
      NGINX_PORT="$2"
      shift 2
      ;;
    --bridge-port)
      BRIDGE_PORT="$2"
      shift 2
      ;;
    --skip-install)
      SKIP_INSTALL=true
      shift
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# Detect OS
detect_os() {
  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    if [[ -f /etc/os-release ]]; then
      . /etc/os-release
      echo "$ID"
    else
      echo "linux"
    fi
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "macos"
  else
    echo "unknown"
  fi
}

install_nginx() {
  local os
  os=$(detect_os)

  case "$os" in
    ubuntu|debian)
      apt-get update
      apt-get install -y nginx
      NGINX_CONF_DIR="/etc/nginx"
      SITES_AVAILABLE="/etc/nginx/sites-available"
      SITES_ENABLED="/etc/nginx/sites-enabled"
      ;;
    fedora|rhel|centos)
      if command -v dnf &>/dev/null; then
        dnf install -y nginx
      else
        yum install -y nginx
      fi
      NGINX_CONF_DIR="/etc/nginx"
      SITES_AVAILABLE="/etc/nginx/conf.d"
      SITES_ENABLED="/etc/nginx/conf.d"
      ;;
    macos)
      if ! command -v brew &>/dev/null; then
        echo "Homebrew required. Install from https://brew.sh"
        exit 1
      fi
      brew install nginx
      NGINX_CONF_DIR="$(brew --prefix)/etc/nginx"
      SITES_AVAILABLE="$NGINX_CONF_DIR/servers"
      SITES_ENABLED="$NGINX_CONF_DIR/servers"
      mkdir -p "$SITES_AVAILABLE"
      ;;
    *)
      echo "Unsupported OS: $os"
      echo "Install Nginx manually, then run with --skip-install"
      exit 1
      ;;
  esac
}

# Build Nginx config
build_nginx_config() {
  local server_name="_"
  local default_opt=""
  [[ -n "$DOMAIN" ]] && server_name="$DOMAIN"
  [[ -z "$DOMAIN" ]] && default_opt=" default_server"

  cat << NGINX_EOF
# pawd-bridge reverse proxy
# Generated by install-nginx-bridge.sh

server {
    listen ${NGINX_PORT}${default_opt};
    server_name ${server_name};

    # Increase timeouts for SSE (/api/events)
    proxy_connect_timeout 60s;
    proxy_send_timeout 3600s;
    proxy_read_timeout 3600s;

    location / {
        proxy_pass http://127.0.0.1:${BRIDGE_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # Required for SSE (Server-Sent Events)
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Connection '';
        chunked_transfer_encoding off;
    }
}
NGINX_EOF
}

# Main
main() {
  echo "pawd-bridge Nginx setup"
  echo "  Bridge port: $BRIDGE_PORT"
  echo "  Nginx port:  $NGINX_PORT"
  [[ -n "$DOMAIN" ]] && echo "  Domain:      $DOMAIN"

  if [[ "$SKIP_INSTALL" != "true" ]]; then
    echo ""
    echo "Installing Nginx..."
    install_nginx
  fi

  os=$(detect_os)
  if [[ "$os" == "macos" ]]; then
    NGINX_CONF_DIR="$(brew --prefix 2>/dev/null)/etc/nginx"
    SITES_AVAILABLE="${NGINX_CONF_DIR}/servers"
    SITES_ENABLED="${NGINX_CONF_DIR}/servers"
    mkdir -p "$SITES_AVAILABLE"
  elif [[ -d /etc/nginx/conf.d ]]; then
    SITES_AVAILABLE="/etc/nginx/conf.d"
    SITES_ENABLED="/etc/nginx/conf.d"
  else
    SITES_AVAILABLE="/etc/nginx/sites-available"
    SITES_ENABLED="/etc/nginx/sites-enabled"
  fi

  CONFIG_FILE="$SITES_AVAILABLE/pawd-bridge.conf"

  # Disable default site to avoid "conflicting server name _" warning
  for f in /etc/nginx/sites-enabled/default /etc/nginx/conf.d/default.conf; do
    if [[ -f "$f" ]]; then
      echo "Disabling default site: $f"
      rm -f "$f" 2>/dev/null || true
    fi
  done

  echo ""
  echo "Writing config to $CONFIG_FILE..."
  build_nginx_config | tee "$CONFIG_FILE" > /dev/null

  # Enable site (Debian/Ubuntu sites-enabled)
  if [[ -d /etc/nginx/sites-enabled ]] && [[ "$SITES_AVAILABLE" == "/etc/nginx/sites-available" ]]; then
    ln -sf "$CONFIG_FILE" "/etc/nginx/sites-enabled/pawd-bridge.conf" 2>/dev/null || true
  fi

  echo ""
  echo "Testing Nginx config..."
  nginx -t

  echo ""
  echo "Reloading Nginx..."
  if [[ $(detect_os) == "macos" ]]; then
    brew services restart nginx 2>/dev/null || nginx -s reload
  else
    systemctl reload nginx 2>/dev/null || service nginx reload
  fi

  echo ""
  echo "Done. Bridge is exposed at:"
  if [[ -n "$DOMAIN" ]]; then
    echo "  http://${DOMAIN}:${NGINX_PORT}"
  else
    echo "  http://<your-server-ip>:${NGINX_PORT}"
  fi
  echo ""
  echo "Ensure the bridge is running: cd pawd-bridge && pnpm start"
  if [[ -n "$DOMAIN" ]]; then
    echo "For HTTPS with Let's Encrypt, run: sudo certbot --nginx -d $DOMAIN"
  fi
}

main
